# uv pip install "requests>=2.20.1"
# uv pip install "mwparserfromhell>=0.5.2"
# uv pip install packaging
# uv pip install importlib_metadata
# uv pip install "wikitextparser>=0.47.5"
# uv pip install pywikibot